#!name=去酷安广告
#!desc=WIP
#!url=https://raw.githubusercontent.com/simouse/iOS-proxy-remove-ads/master/shadowrocket/coolapk.module

# RuCu6 可参考 https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/coolapk.js
# 墨鱼可参考 https://github.com/ddgksf2013/Scripts/raw/master/coolapk.js

[MITM]
hostname = %APPEND% api.coolapk.com

[URL Rewrite]
# 搜索时出现的文字小气泡推荐（可选）
#^https?:\/\/api\.coolapk\.com\/v6\/search\?.*type=hotSearch _ reject-dict

[Script]
rucu6mod=type=http-response,pattern=^https?:\/\/api\.coolapk\.com\/v6\/,requires-body=1,script-path=https://raw.githubusercontent.com/simouse/iOS-proxy-remove-ads/master/scripts/coolapk.js