#!name=去酷安广告
#!desc=WIP
#!url=https://raw.githubusercontent.com/simouse/iOS-proxy-remove-ads/master/shadowrocket/coolapk.module

[MITM]
hostname = %APPEND% api.coolapk.com

[URL Rewrite]
# 搜索时出现的卡片推荐（可选）
#^https?:\/\/api\.coolapk\.com\/v6\/search\?.*type=hotSearch _ reject-dict

[Script]
# 开屏广告
splashAd=type=http-response,pattern=^https?:\/\/api\.coolapk\.com\/v6\/main\/init,requires-body=1,script-path=https://raw.githubusercontent.com/simouse/iOS-proxy-remove-ads/master/scripts/coolapk.js

# 其他广告（可选），注释此项可以支持平台的运营
# RuCu6 https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/coolapk.js
# 墨鱼 https://raw.githubusercontent.com/ddgksf2013/Scripts/master/coolapk.js
otherAds=http-response,pattern=^https:\/\/api\.coolapk\.com\/v6\/(((page\/)?dataList)|(main\/(dataList|indexV8))|(feed\/(detail|replyList))),requires-body=1,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/coolapk.js
